# Generated by Django 4.2.5 on 2023-10-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxonaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='qayatrish_sana',
            new_name='qaytarish_sana',
        ),
    ]
